### ISSUE TITLE
Yaml Builder release ETA

### ISSUE THREAD

**Issue by christianacca** [csharpfritz/Fritz.ConfigurationBuilders#9]
Keen on starting to use that Yaml builder you were [working on](http://jeffreyfritz.com/2017/11/beginning-to-configure-net-framework-applications-with-yaml/) :-) Do you have an ETA for getting a release?

Thanks
Christian

**Comment by csharpfritz** [comment]
I'll schedule some more work for Tuesday the 16th on stream at live.jeffreyfritz.com.  If you have any comments or feedback about how I should direct that feature, add them here and we'll write it live on video.

**Comment by christianacca** [comment]
Hi Jeff,

My main requirements for the yaml builder are as follows:

- [x] support specifying the location of the yaml file that will be used to inject values
  - [x] support absolute file path
  - [x] support relative file path (relative to the web.config)
- [x] allow multiple yaml file builders to apply to the same web.config section
- [x] support mapping sections in a web.config *hierarchy* to corresponding "sections" in a yaml file
  - ie I don't want to *have* to create multiple yaml files, one for each section that I want to inject config values into
- [x] option to skip the yaml builder if it's file source does not exist
- ~trigger recycle of AppDomain when the yaml file changes~
  - ~allow this to be configurable (maybe via [restartOnExternalChanges](https://msdn.microsoft.com/en-us/library/system.configuration.sectioninformation.restartonexternalchanges.aspx) attribute)~


My higher level context is being able to use docker *swarm* [config](https://docs.docker.com/engine/swarm/configs/) and [secret](https://docs.docker.com/engine/swarm/secrets/) support to inject yaml files into the containers that need them.

I've listed in my (selfish) priority order, if that helps ;-)

Thanks
Christian

**Comment by christianacca** [comment]
Scrub this from (my) list:

> trigger recycle of AppDomain when the yaml file changes

that doesn't make sense in the world of containers.

**Comment by csharpfritz** [comment]
The new Samples-Yaml project demonstrates the use of multiple YAML configurationBuilders with 1 appSettings section

**Comment by csharpfritz** [comment]
If you choose to use two configurationBuilders on the same section, the last one referenced takes priority

**Comment by csharpfritz** [comment]
Committed changes in the feature_yaml branch... still working on a few more, and will hit that next time

**Comment by christianacca** [comment]
Thanks Jeff for the coding session - moving this feature on nicely

**Comment by csharpfritz** [comment]
I think we have met all of the features now... need to write some docs for this.  Check the samples-yaml to see how to use a YAML section.  I'm only supporting top-level sections for now.

I'll merge the branch and push a 0.4 build to NuGet later.  Thanks for the interest!

**Comment by christianacca** [comment]
Thanks Jeff that's great.

> I'm only supporting top-level sections for now

So just to confirm, that means you're not yet able to inject *multiple* strongly typed application settings (children of `configuration > applicationSettings`) with a **single yaml file**? In the case, I would have to have separate yaml files for each of these sections?

**Comment by csharpfritz** [comment]
What do you mean by "strongly-typed application settings"?

You can structure your YAML like:
appSettings
  setting1: value1
connectionStrings
  db1: connectionString1

and you can configure two different YAML ConfigurationBuilders to each read
the same doc, and each grab a different section to apply.  Check the
samples-YAML folder to see how I apply the sections.yml file


Jeff

**Comment by christianacca** [comment]
> What do you mean by "strongly-typed application settings"?

Application settings: https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/application-settings-architecture

So for example here's what [part] of my web.config looks like:

``` xml
<configuration>
  <applicationSettings>
    <Ram.Series5.Spa.Properties.Settings>
      <setting name="ActiveDirectoryEnabled" serializeAs="String">
        <value>False</value>
      </setting>
    </Ram.Series5.Spa.Properties.Settings>
  </applicationSettings>
```

**Comment by csharpfritz** [comment]
There is a mode="expand" option that comes with our ConfigurationBuilders, including the base one that these are built off of.  If you set that you can use ${token} notation wherever you want the ConfigurationBuilder to replace a value and it will do a string replace of those tokens

**Comment by christianacca** [comment]
Have you got an example of that (ideally with the yaml builder)?

**Comment by christianacca** [comment]
Hi Jeff, when do you plan to release 0.4 to nuget gallery?

**Comment by csharpfritz** [comment]
Just pushed.. thanks for the interest!

**Comment by ccrowhurstram** [comment]
Just been experimenting with a combination of `mode="expand" jsonMode="Sectional"` with a web.config

``` xml
<configuration>
  <applicationSettings configBuilders="MySettings">
    <Ram.Series5.Spa.Properties.Settings>
      <setting name="ActiveDirectoryEnabled" serializeAs="String">
        <value>False</value>
      </setting>
    </Ram.Series5.Spa.Properties.Settings>
     <!-- more settings here -->
  </applicationSettings>
```

It seems that combination will not work - I get the a 500.19 "Unrecognized attribute 'configBuilders'"

**Comment by ccrowhurstram** [comment]
Sorry, of course I was working with the json builder...

**Comment by ccrowhurstram** [comment]
So it looks like I'm going to be out of luck using configurationbuilders with a *single* yaml or json file - I won't be able to apply the builder to the `applicationSettings` element

**Comment by csharpfritz** [comment]
Works for me:

```xml
<configBuilders>
  <builders>
    <add name="Yaml1" mode="expand" location="simple.yml"
    type="Fritz.ConfigurationBuilders.YamlConfigurationBuilder, Fritz.ConfigurationBuilders"/>
  </builders>
</configBuilders>
<applicationSettings>
  <WinForm.Properties.Settings configBuilders="Yaml1">
    <setting name="MyFirstSetting" serializeAs="String">
      <value>${setting1}</value>
    </setting>
  </WinForm.Properties.Settings>
</applicationSettings>
```

**Comment by csharpfritz** [comment]
My test project to verify ApplicationSettings is at: https://github.com/csharpfritz/Fritz.ConfigurationBuilders/tree/master/samples/Winform

**Comment by ccrowhurstram** [comment]
Yeah, that's what I got working when I was experimenting.

What I still can't do is have a single yaml file and map one section from that file to say `applicationSettings>MySettings1`, another section to `applicationSettings>MySettings2`, etc.

I suspect I could create a flat yaml file and use a combination of `Prefix` and `StripPrefix` as a workaround... I'd just be missing much of goodness of yaml.

**Comment by ccrowhurstram** [comment]
I seem to be getting 500.19 "Unrecognized attribute 'configBuilders'" a lot.

For example, I've just tried:

``` xml
<system.webServer>
  <rewrite configBuilders="RewriteSettings">
```

Am I missing something with how to setup ConfigurationBuilders or is this feature going to always be limited due to the validation of the xml against a schema that is locked down to exclude unknown xml attributes?

**Comment by csharpfritz** [comment]
Let us know where you’re seeing that, we have it working on the top-level ConfigurationManager entries. Other providers that read the file could be more sensitive 



Jeff

**Comment by ccrowhurstram** [comment]
So far I've seen it on:

* `system.webServer>rewrite`
* `applicationSettings`
* `system.web>healthMonitoring`

You can see in Visual Studio, as you are editing the web.config, whether the element is going to cause the 500.19 - the `configBuilders` attribute is underlined with a blue squiggle.

At a guess, I think all elements that are specific to ASP.Net are NOT going to allow the `configBuilders` attribute.

**Comment by ccrowhurstram** [comment]
Jeff, slightly off tangent but I read a [blog post](http://benfoster.io/blog/net-core-configuration-legacy-projects) that explained how you could use the Asp.Net Core ConfigurationBuilder nuget libraries (`Microsoft.Extensions.Configuration.*`) in ASP.Net (non-core). 

If that is the case, that might be an *alternative* to using ConfigurationBuilders so long as a project can tolerate a refactoring session over to using POCO classes for configuration.

However, I couldn't reference these nuget packages, even though I'm target 4.7.1 which is compatible with netstandard 2. **Can you confirm whether this is indeed possible?**

Package manager complains with the error:

``` cmd
Install-Package : Could not install package 'Microsoft.Extensions.Configuration.Json 2.0.0'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.7.1', but the package does not contain any assembly references or content files that are compatible with that framework
```
